version: '3.8'

services:
  feitosa-dm:
    build: .
    container_name: feitosa-directory-manager
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "53:53"
      - "53:53/udp"
      - "88:88"
      - "88:88/udp"
      - "135:135"
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "389:389"
      - "389:389/udp"
      - "445:445"
      - "464:464"
      - "464:464/udp"
      - "636:636"
    volumes:
      - samba_data:/var/lib/samba
      - samba_etc:/etc/samba
      - backend_db:/app/backend/data
    environment:
      - JWT_SECRET_KEY=feitosa_auto_generate_in_production
      - JWT_EXPIRE_HOURS=2.0

  caddy:
    image: caddy:2-alpine
    container_name: feitosa-caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    command: caddy reverse-proxy --from :80 --to feitosa-dm:8000
    # O Caddy ira automaticamente gerenciar um certificado local
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  samba_data:
  samba_etc:
  backend_db:
  caddy_data:
  caddy_config:
